version: '3'
services:
  backend:
    build: .
    ports:
      - 9000:9000
    volumes:
      - ./play-crud:/home/arturgorowski/ebiznes/play-crud
    working_dir: /home/arturgorowski/ebiznes/play-crud
    command: bash -c "sbt run"
