version: '3'
services:
  frontend:
    build: .
    ports:
      - 4200:4200
    volumes:
      - ./angular-shop:/home/arturgorowski/projekt/angular-shop
    working_dir: /home/arturgorowski/projekt/angular-shop
    command: bash -c "npm install && ng serve --port 4200"
